### ISSUE TITLE
cant fix installation thru manager

### ISSUE THREAD

**Issue by endo9000** [tzwm/comfyui-profiler#17]
it seems i cannot install the node properly. 
after installing and restarting comfyui i always get the same 'error'
![image](https://github.com/user-attachments/assets/62f92bf6-9f57-4d21-b67e-8996c7248c35)
not sure what else i need to provide for proper support, so please if there are any questions feel free to ask! 🙏

**Comment by jelling** [comment]
+1

**Comment by endo9000** [comment]
okay gotcha! i hope this gets updated in time. 🙌

**Comment by endo9000** [comment]
okay gotcha! i hope this gets updated in time. 🙌
